# Base configs
baseurl: "https://portfolio.fnfd.se"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-168145464-1"

# UI configs
title: "Foton av Joachim 'Joshi' Friberg"
subtitle: "Stillbilder från livet"
author: "Joachim Friberg"
header:
 title: "FnFD Foto"
 subtitle: "Av Joachim 'Joshi' Friberg"
footer:
 name: "Hej där!"
 bio: "Jag är en mångsysslare och foto är en av mina passioner. Hör av er om ni önskar att jag tar just era bilder, eller filmer!"
 github: "Denna sidan är genererad med hjälp av Ramparta\'s portfoliogenerator. Kontakta mig för mer info!"
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/joachim.friberg.42"
  twitter: ""
  instagram: "https://www.instagram.com/fnfd.se"
  dribbble: ""
  linkedin: "https://www.linkedin.com/in/joachim-friberg-ab260198/"
  github: "https://www.github.com/joshiegy"
